name: Compilations tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest CMake
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: latestrc

      - uses: actions/checkout@v3
      - name: Install raylib dependencies and perform make at the root of the repository
        run:  |
          sudo apt install libasound2-dev libx11-dev libxrandr-dev libxi-dev libgl1-mesa-dev libglu1-mesa-dev libxcursor-dev libxinerama-dev
          git clone https://github.com/raysan5/raylib.git raylib
          cd raylib
          mkdir build && cd build
          cmake -DBUILD_SHARED_LIBS=ON ..
          make
          sudo make install
        timeout-minutes: 2
